/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:f18ef6fd-3732-46f1-90b8-87ab8b072def",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_Gr9WPsz3i",
    "aws_user_pools_web_client_id": "4qddbhldc4os0sn5t7p4liv2b3",
    "oauth": {}
};


export default awsmobile;
