// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
  aws_project_region: 'eu-central-1',
  aws_cognito_identity_pool_id: 'eu-central-1:75a6c653-26fd-48e1-9f17-274db2ca4ae8',
  aws_cognito_region: 'eu-central-1',
  aws_user_pools_id: 'eu-central-1_Gr9WPsz3i',
  aws_user_pools_web_client_id: '4qddbhldc4os0sn5t7p4liv2b3',
  oauth: {
    domain: 'detective-collective-develop.auth.eu-central-1.amazoncognito.com',
    scope: [
      'phone',
      'email',
      'openid',
      'profile',
      'aws.cognito.signin.user.admin'
    ],
    redirectSignIn: 'http://localhost:4200/',
    redirectSignOut: 'http://localhost:4200/',
    responseType: 'code'
  },
  federationTarget: 'COGNITO_USER_POOLS'
};
export default awsmobile;
